services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\NewsSeo\:
    resource: '../Classes/*'

  GeorgRinger\NewsSeo\EventListener\NewsDetailActionEventListener:
    tags:
      - name: event.listener
        identifier: 'newsseo-newsdetailaction'
        event: GeorgRinger\News\Event\NewsDetailActionEvent

  GeorgRinger\NewsSeo\EventListener\ModifyUrlForCanonicalTagEventListener:
    tags:
      - name: event.listener
        identifier: 'newsseo-newsdetailcanonicalaction'
        event: TYPO3\CMS\Seo\Event\ModifyUrlForCanonicalTagEvent
